=== daniel8691/customerOrders/order_assignment.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.example.org/order_assignment" 
		xmlns:tns="http://www.example.org/order_assignment" 
			elementFormDefault="qualified">
	
	
	<element name = "order" type="tns:Orders"/>
	<complexType name="Orders">
		<sequence>
			<element name="Products" type="tns:Products" minOccurs = "1" maxOccurs="unbounded"/>
			<element name="customer" type = "tns:customer"/>
		</sequence>
		<attribute name="id" type="tns:order_id"></attribute>
	</complexType>
	
	
	<complexType name = "Products">
		<sequence>
			<element name = "name" type="tns:descriptionLength"/>
			<element name = "description" type="tns:descriptionLength"/>
			<element name = "price" type="int"/>
			<element name = "category" type="tns:CategoryTypes"/>
		</sequence>	
		<attribute name="id" type="tns:order_id"></attribute>
	</complexType>
	<complexType name="customer">
		<all>
			<element name="name" type="string"/>
			<element name='phone' type = 'string'/>
			
		</all>
		<attribute name="id" type="tns:order_id"></attribute>
	</complexType>
	
	
	
	<!-- Set id restriction to have a number limit of 50 -->
	<simpleType name="order_id">
		<restriction base="int">
			<maxInclusive value="50"/>
		</restriction>
	</simpleType>
	
	<simpleType name = "nameLength">
		<restriction base='string'>
			<maxLength value="20"></maxLength>
		</restriction>
	</simpleType>
	
	<simpleType name = "descriptionLength">
		<restriction base='string'>
			<maxLength value="100"></maxLength>
		</restriction>
	</simpleType>
	
	<simpleType name = "CategoryTypes">
		<restriction base="string">
			<enumeration value="electronics"/>
			<enumeration value="books"/>
			<enumeration value="shoes"/>
			
		</restriction>
	
	</simpleType>
	





</schema>

=== daniel8691/customerOrders/orderNumbers.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:order xmlns:tns="http://www.example.org/order_assignment" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/order_assignment order_assignment.xsd ">
  <tns:Products>
    <tns:name>tns:name</tns:name>
    <tns:description>tns:description</tns:description>
    <tns:price>0</tns:price>
    <tns:category>electronics</tns:category>
  </tns:Products>
  <tns:Products>
    <tns:name>tns:name</tns:name>
    <tns:description>tns:description</tns:description>
    <tns:price>0</tns:price>
    <tns:category>electronics</tns:category>
  </tns:Products>
  <tns:Products>
    <tns:name>tns:name</tns:name>
    <tns:description>tns:description</tns:description>
    <tns:price>0</tns:price>
    <tns:category>electronics</tns:category>
  </tns:Products>
  <tns:customer>
    <tns:name>tns:name</tns:name>
    <tns:phone>tns:phone</tns:phone>
  </tns:customer>
</tns:order>
